### ISSUE TITLE
cros module got removed from deno 

### ISSUE THREAD

**Issue by mhmo91** [tajpouria/cors#17]
https://deno.land/x/cors/mod.ts is no longer available, message from the deno repo says

```error
No uploaded versions
This module name has been reserved for a repository, but no versions have been uploaded yet. Modules that do not upload a version within 30 days of registration will be removed. If you are the owner of this module, please re-link the GitHub repository with deno.land/x, and publish a new version.

```

**Comment by narwy** [comment]
@tajpouria major issue can you fix please

**Comment by tajpouria** [comment]
@mhmo91 @narwy Thank you guys for reporting, I will follow Deno instruction right now and make a result announcement here ASAP.

**Comment by narwy** [comment]
Thanks @tajpouria any luck?

**Comment by narwy** [comment]
@tajpouria There was an issue, it's now fixed and working. Cheers.

**Comment by tajpouria** [comment]
@narwy @mhmo91  Sorry for the delay! I just released cors@v1.0.0
```ts
import { oakCors } from 'https://deno.land/x/cors@v1.0.0/mod.ts'
```
By the way, I don't really what is wrong with https://deno.land/x/cors UI it's not show anything!

**Comment by narwy** [comment]
@tajpouria the UI has been fixed it was a bug :)

**Comment by tajpouria** [comment]
@narwy Still getting this
![Screenshot from 2020-08-04 02-29-13](https://user-images.githubusercontent.com/46822325/89231402-7df57500-d5fa-11ea-8fd3-25f80915eb19.png)

**Comment by narwy** [comment]
@tajpouria You'll need to clear your cache and do a hard refresh: https://deno.land/x/cors@v1.1.0
